apiVersion: v1
kind: Service
metadata:
  name: app-food-service
spec:
  selector:
    app: app-food-selector
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30001
  type: NodePort
