apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-food-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-food-selector
  template:
    metadata:
      labels:
        app: app-food-selector
    spec:
      containers:
      - name: postgres-db
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: food
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      - name: app-food
        image: brunomatiasdev/tech-challenge-repo:latest
        ports:
        - containerPort: 8091
      volumes:
      - name: postgres-storage
      - name: redis-storage
        emptyDir: {}
      