apiVersion: v1
kind: Service
metadata:
  name: postgres-food-service
spec:
  selector:
    app: app-food-selector
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer