apiVersion: v1
kind: Service
metadata:
  name: redis-food-service
spec:
  selector:
    app: app-food-selector
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer