
CREATE TABLE IF NOT EXISTS cliente
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    cpf           VARCHAR(255),
    nome          VARCHAR(255),
    email         VARCHAR(255),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro  TIMESTAMP WITHOUT TIME ZONE,
    cliente        BIGINT,
    status_pedido VARCHAR(255),
    CONSTRAINT pk_pedido PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS produto
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    nome          VARCHAR(255),
    descricao     VARCHAR(500),
    preco         DECIMAL,
    categoria     VARCHAR(255),
    imagem        VARCHAR(255),
    CONSTRAINT pk_produto PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pedido_produto
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    pedido_id     BIGINT,
    produto_id    BIGINT,
    quantidade    INTEGER                                 NOT NULL,
    CONSTRAINT pk_pedido_produto PRIMARY KEY (id)
);

ALTER TABLE pedido
    ADD CONSTRAINT FK_PEDIDO_ON_CLIENTE FOREIGN KEY (cliente) REFERENCES cliente (id);

ALTER TABLE pedido_produto
    ADD CONSTRAINT FK_PEDIDO_PRODUTO_ON_PEDIDO FOREIGN KEY (pedido_id) REFERENCES pedido (id);

ALTER TABLE pedido_produto
    ADD CONSTRAINT FK_PEDIDO_PRODUTO_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produto (id);


