CREATE TABLE credenciais_acesso
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    nome          VARCHAR(255),
    token         TEXT,
    usuario       VARCHAR(255),
    CONSTRAINT pk_credenciaisacesso PRIMARY KEY (id)
);

ALTER TABLE credenciais_acesso
    ADD CONSTRAINT uc_credenciaisacesso_usuario UNIQUE (usuario);

CREATE TABLE escopo_loja_mercado_pago
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255),
    external_id   VARCHAR(255),
    user_id       BIGINT,
    street_number VARCHAR(255),
    street_name   VARCHAR(255),
    city_name     VARCHAR(255),
    state_name    VARCHAR(255),
    latitude      DOUBLE PRECISION                        NOT NULL,
    longitude     DOUBLE PRECISION                        NOT NULL,
    reference     VARCHAR(255),
    CONSTRAINT pk_escopolojamercadopago PRIMARY KEY (id)
);

CREATE TABLE dia_semana
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    dia           VARCHAR(255),
    CONSTRAINT pk_dia_semana PRIMARY KEY (id)
);

CREATE TABLE intervalo
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_cadastro    TIMESTAMP WITHOUT TIME ZONE,
    open             time WITHOUT TIME ZONE,
    close            time WITHOUT TIME ZONE,
    dia_da_semana_id BIGINT,
    CONSTRAINT pk_intervalo PRIMARY KEY (id)
);

ALTER TABLE intervalo
    ADD CONSTRAINT FK_INTERVALO_ON_DIA_DA_SEMANA FOREIGN KEY (dia_da_semana_id) REFERENCES dia_semana (id);

CREATE TABLE loja_to_business_hours
(
    dia_semana_id BIGINT NOT NULL,
    loja_id       BIGINT NOT NULL
);

ALTER TABLE loja_to_business_hours
    ADD CONSTRAINT uc_loja_to_business_hours_dia_semana UNIQUE (dia_semana_id);

ALTER TABLE loja_to_business_hours
    ADD CONSTRAINT fk_lojtobushou_on_dia_da_semana FOREIGN KEY (dia_semana_id) REFERENCES dia_semana (id);

ALTER TABLE loja_to_business_hours
    ADD CONSTRAINT fk_lojtobushou_on_escopo_loja_mercado_pago FOREIGN KEY (loja_id) REFERENCES escopo_loja_mercado_pago (id);